export const RESTORE_WINDOW = 'RESTORE_WINDOW'
export const MINIMIZE_WINDOW = 'MINIMIZE_WINDOW'
export const MAXIMIZE_WINDOW = 'MAXIMIZE_WINDOW'
export const CLOSE_WINDOW = 'CLOSE_WINDOW'

export const WINDOW_MAXIMIZE = 'WINDOW_MAXIMIZE'
export const WINDOW_UNMAXIMIZE = 'WINDOW_UNMAXIMIZE'
